services:
  - type: web
    name: phoree-chatbot-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://phoree-chatbot-api.onrender.com

  - type: web
    name: phoree-chatbot-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/chat.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: "10000" 