services:
  - type: web
    name: phoree-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/chat.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
    plan: free 